ccflags-y += -Idrivers/media/platform/msm/camera_v2/
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor_caf
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor_caf/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_dt_util.o
